### PR TITLE
helm update version

### PR DESCRIPTION
**Pull request by bstascavage**
## what
* Updating helm to the latest version, 3.6.3

## why
* Fossa Helm Chart requires helm version 3.5+

## references
* [Helm Tag 3.6.3](https://github.com/helm/helm/tree/v3.6.3)

### CODE REVIEW

**Review by scaneer — COMMENTED** [review]
Brad suggested taking out the codefresh section to see if it would pass, but it did not change the behavior I was seeing so I don't know if we want to keep those changes.

**Review by saic-statonb — APPROVED** [review]
LGTM

**Pull request merged**
