### PR TITLE
Initial migration

### PR DESCRIPTION
**Pull request by RothAndrew**
## what
- Initial migration of code from GitLab
- Addition of taskfile tasks and codefresh config to enable codefresh pipeline

## why
- Open source woo! 🎉 

## other notes
- Requires custom codefresh pipeline due to needing to build a docker image (which can't be done without using Codefresh's special "build" step, and then needing to run the automated tests inside the new image

## references
N/A

### CODE REVIEW

**Comment by RothAndrew** [comment]
Requesting security audit review from @saic-oss/compliance per onboarding guide instructions

**Review by jesse-chauvin — APPROVED** [review]
Approved

**Pull request merged**
