### PR TITLE
Add Codefresh pipelines for master branch and tag releases

### PR DESCRIPTION
**Pull request by RothAndrew**
## what
- Add pipelines for the master branch and tags

## why
- so that builds are pushed properly to docker hub

## references
N/A

### CODE REVIEW

**Review by jesse-chauvin — DISMISSED** [review]
Good

**Comment by RothAndrew** [comment]
@jesse-chauvin sorry, one more please. Was missing an environment variable

**Review by jesse-chauvin — APPROVED** [review]
Got it, Saw the change

**Pull request merged**
