### PR TITLE
Updating Terraform and Terraform-related tools

### PR DESCRIPTION
**Pull request by bstascavage**
## what
* Updating Terraform and Terraform related binaries
    * `terraform`: 0.15.4
    * `terraform-docs`: 0.12.1 (**NOTE**: This is one version previous than the newest due to the newest version not loading properly)
    * `tflint`: 0.28.1
    * `tfsec`: 0.39.37

## why
* The current versions of Terraform and it's related binaries were all over a year old.

## references
* None

### CODE REVIEW

**Review by flintkr — DISMISSED** [review]

**Comment by RothAndrew** [comment]
> /test

@flintkr you need to set your org visibility to public for codefresh to see you as a valid person that can trigger this pipeline

**Review by flintkr — APPROVED** [review]

**Pull request merged**
